language: java
jdk:
- oraclejdk8
addons:
  ssh_known_hosts: project.oooooreo.xyz
before_install:
  - openssl aes-256-cbc -K $encrypted_906226319d35_key -iv $encrypted_906226319d35_iv -in id_rsa.enc -out $TRAVIS_BUILD_DIR/id_rsa -d
  - chmod 600 $TRAVIS_BUILD_DIR/id_rsa
script:
- mvn test
- mvn compile war:war -DskipTests=true -f pom-docker.xml
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./script/deploy.sh
  on:
    branch: master
notifications:
  email:
  - Icear.Github@outlook.com



