language: java

jdk:
  - oraclejdk8

script:
  - mvn test
  - mvn clean package -DskipTests=true -f pom-docker.xml

deploy:
  provider: script
  skip_cleanup: true
  script:
    - sshpass -p $PASSWORD scp -P $PORT -r ./target/ROOT.war $USER@$SERVER:$DEPLOY_FILE_LOCATION
    - ssh $USER@$SERVER $DEPLOY_SCRIPT_LOCATION --branch TRAVIS_BRANCH
  on:
    branch: master

addons:
  ssh_known_hosts: $SERVER:$PORT

notifications:
    email:
    - Icear.Github@outlook.com