language: java
jdk:
- oraclejdk8
script:
- mvn test
- mvn clean package -DskipTests=true -f pom-docker.xml
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./script/deploy.sh
  on:
    branch: master
addons:
  ssh_known_hosts: $SERVER
notifications:
  email:
  - Icear.Github@outlook.com
before_install:
  - openssl aes-256-cbc -K $encrypted_906226319d35_key -iv $encrypted_906226319d35_iv -in id_rsa.enc -out ./script/id_rsa -d
  - chmod 600 ./script/id_rsa
